### ISSUE TITLE
Проблема с public function setStateListener($event, $listener)

### ISSUE THREAD

**Issue by pitonn** [Konstantin-Vl/yii2-ulogin-widget#1]
Здравствуйте. У меня почему-то не работает метод setStateListener со строкой
`$js = sprintf(
			'uLogin.setStateListener(%s, %s, %s);',
			$this->id,
			$event,
			$listener
		);`
если изменить на
`$js = sprintf(
			'uLogin.setStateListener("%s", "%s", %s);',
			$this->id,
			$event,
			$listener
		);`, то все становится нормально.

**Comment by Konstantin-Vl** [comment]
Странно, все вроде работало)
Сегодня и вечером или завтра разберусь

**Comment by Konstantin-Vl** [comment]
Fixed https://github.com/Konstantin-Vl/yii2-ulogin-widget/pull/3
